// The app's interface icons, under the names the rest of the code already
// imports. Each one is a Lucide icon, so every icon in the app shares one
// drawing style and takes its color from the text around it.
export {
  House as HomeIcon,
  Wallet as WalletIcon,
  Receipt as ReceiptIcon,
  ShoppingBag as BagIcon,
  LayoutGrid as GridIcon,
  Settings as CogIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  ChevronDown as ChevronDownIcon,
  Plus as PlusIcon,
  Zap as BoltIcon,
  ShieldCheck as ShieldIcon,
  Calendar as CalendarIcon,
  Trash2 as TrashIcon,
  Check as CheckIcon,
  X as XIcon,
  TrendingUp as TrendingUpIcon,
  Users as UsersIcon,
  TriangleAlert as AlertIcon,
  Pencil as PencilIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  ArrowLeftRight as SwitchIcon,
  LogOut as LogOutIcon,
  Mail as MailIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
} from 'lucide-react';
